// const Arsenal = 'Arsenal Football Club is a professional football club based in Islington, London, England that plays in the Premier League, the top flight of English football. The club has won 13 league titles (including one unbeaten title), a record 14 FA Cups, two League Cups, 16 FA Community Shields, the League Centenary Trophy, one European Cup Winners\' Cup, and one Inter-Cities Fairs Cup.'+
// ''+
// 'Arsenal was the first club from the South of England to join The Football League, in 1893, and they reached the First Division in 1904. Relegated only once, in 1913, they continue the longest streak in the top division,[3] and have won the second-most top-flight matches in English football history.[4] In the 1930s, Arsenal won five League Championships and two FA Cups, and another FA Cup and two Championships after the war. In 1970–71, they won their first League and FA Cup Double. Between 1989 and 2005, they won five League titles and five FA Cups, including two more Doubles. They completed the 20th century with the highest average league position.[5]'+
// ''+
// 'Herbert Chapman, who changed the fortunes of Arsenal forever, won the club its first silverware, and his legacy led the club to dominate the 1930s decade; Chapman, however, died of pneumonia in 1934, aged 55. He helped introduce the WM formation, floodlights, and shirt numbers;[6] he also added the white sleeves and brighter red to the club\'s jersey.[7] Arsène Wenger was the longest-serving manager and won the most trophies. He won a record seven FA Cups, and his title-winning team set an English record for the longest top-flight unbeaten league run at 49 games between 2003 and 2004,[8] receiving the nickname The Invincibles.'+
// ''+
// 'In 1886 munitions workers at the Royal Arsenal in Woolwich founded the club as Dial Square. In 1913, the club crossed the city to Arsenal Stadium in Highbury, becoming close neighbours of Tottenham Hotspur, and creating the North London derby. In 2006, they moved to the nearby Emirates Stadium. In terms of revenue, Arsenal is the ninth highest-earning football club in the world, earned €487.6m in 2016–17 season.[9] Based on social media activity from 2014 to 2015, Arsenal\'s fanbase is the fifth largest in the world.[9] In 2018, Forbes estimated the club was the third most valuable in England, being worth US$2.24 billion.[10] The motto of the club has long been Victoria Concordia Crescit, Latin for "Victory Through Harmony".';


const Arsenal  = 'Arsenal Football Club is a professional football club based in Islington, London, England that plays in the Premier League, the top flight of English football. The club has won 13 league titles (including one unbeaten title), a record 14 FA Cups, two League Cups, 16 FA Community Shields, the League Centenary Trophy, one European Cup Winners\' Cup, and one Inter-Cities Fairs Cup.'+
    ''+
    'Arsenal was the first club from the South of England to join The Football League, in 1893, and they reached the First Division in 1904. Relegated only once, in 1913, they continue the longest streak in the top division,[3] and have won the second-most top-flight matches in English football history.[4] In the 1930s, Arsenal won five League Championships and two FA Cups, and another FA Cup and two Championships after the war. In 1970–71, they won their first League and FA Cup Double. Between 1989 and 2005, they won five League titles and five FA Cups, including two more Doubles. They completed the 20th century with the highest average league position.[5]'+
    ''+
    'Herbert Chapman, who changed the fortunes of Arsenal forever, won the club its first silverware, and his legacy led the club to dominate the 1930s decade; Chapman, however, died of pneumonia in 1934, aged 55. He helped introduce the WM formation, floodlights, and shirt numbers;[6] he also added the white sleeves and brighter red to the club\'s jersey.[7] Arsène Wenger was the longest-serving manager and won the most trophies. He won a record seven FA Cups, and his title-winning team set an English record for the longest top-flight unbeaten league run at 49 games between 2003 and 2004,[8] receiving the nickname The Invincibles.'+
    ''+
    'In 1886 munitions workers at the Royal Arsenal in Woolwich founded the club as Dial Square. In 1913, the club crossed the city to Arsenal Stadium in Highbury, becoming close neighbours of Tottenham Hotspur, and creating the North London derby. In 2006, they moved to the nearby Emirates Stadium. In terms of revenue, Arsenal is the ninth highest-earning football club in the world, earned €487.6m in 2016–17 season.[9] Based on social media activity from 2014 to 2015, Arsenal\'s fanbase is the fifth largest in the world.[9] In 2018, Forbes estimated the club was the third most valuable in England, being worth US$2.24 billion.[10] The motto of the club has long been Victoria Concordia Crescit, Latin for "Victory Through Harmony".';

const Aston_Villa =   'Aston Villa Football Club is an English professional football club based in Aston, Birmingham. The club competes in the Premier League, the top tier of the English football league system. Founded in 1874, they have played at their home ground, Villa Park, since 1897. Aston Villa were one of the founder members of the Football League in 1888 and of the Premier League in 1992.[5] Villa are one of only five English clubs to have won the European Cup, in 1981–82. They have also won the Football League First Division seven times, the FA Cup seven times, the League Cup five times, and the European (UEFA) Super Cup once.'+
''+
'Villa have a fierce local rivalry with Birmingham City and the Second City derby between the teams has been played since 1879.[6] The club\'s traditional kit colours are claret shirts with sky blue sleeves, white shorts and sky blue socks. Their traditional club badge is of a rampant lion.[7][8] The club is currently owned by the NSWE group, a company owned by the Egyptian billionaire Nassef Sawiris and the American billionaire Wes Edens.'+
'Aston Villa Football Club were formed in March 1874, by members of the Villa Cross Wesleyan Chapel in Handsworth which is now part of Birmingham. The four founders of Aston Villa were Jack Hughes, Frederick Matthews, Walter Price and William Scattergood.[9] Aston Villa\'s first match was against the local Aston Brook St Mary\'s Rugby team. As a condition of the match, the Villa side had to agree to play the first half under Rugby rules and the second half under Association rules.[10] After moving to the Wellington Road ground in 1876, Villa soon established themselves as one of the best teams in the Midlands, winning their first honour, the Birmingham Senior Cup in 1880, under the captaincy of Scotsman George Ramsay.[11]';
	

const brighton = 'Brighton & Hove Albion Football Club (/ˈbraɪtən ... ˈhoʊv/), commonly referred to simply as Brighton, is an English professional football club based in the city of Brighton and Hove. They compete in the Premier League, the top tier of the English football league system. The club\'s home ground is the 30,750-capacity[2] Falmer Stadium, situated in Falmer to the north east of the city.'+
''+
'Founded in 1901, and nicknamed the "Seagulls" or "Albion", Brighton played their early professional football in the Southern League, before being elected to the Football League in 1920. The club enjoyed greatest prominence between 1979 and 1983 when they played in the First Division and reached the 1983 FA Cup Final, losing to Manchester United after a replay.[3] They were relegated from the First Division in the same season.'+
''+
'By the late 1990s, Brighton was in the fourth tier of English football and were having financial difficulties. After narrowly avoiding relegation from the Football League to the Conference in 1997, a boardroom takeover saved the club from liquidation. Successive promotions in 2001 and 2002 brought Brighton back to the second tier, and in 2011, the club moved into the Falmer Stadium after 14 years without a permanent home ground. In the 2016–17 season, Brighton finished second in the EFL Championship and were thus promoted to the Premier League, ending a 34-year absence from the top flight.Brighton & Hove Albion F.C. were founded in 1901 and 19 years later, in 1920, they were elected to the Football League\'s new Third Division – having previously been members of the Southern League. In the Southern League they won their only national honour to date, the FA Charity Shield, which at that time was contested by the champions of the Southern League, and the Football League, by defeating Football League Champions Aston Villa in 1910.[4]';

const burnley = 'Burnley Football Club (/ˈbɜːrnli/) is an English association football club based in Burnley, Lancashire. Founded on 18 May 1882, it was one of the first to become professional (in 1883), and subsequently put pressure on the Football Association to permit payments to players. The club entered the FA Cup for the first time in 1885–86 and was one of the 12 founder members of the Football League in 1888–89. From the 1950s until the 1970s, under chairman Bob Lord, the club became renowned for its youth policy and scouting system, and was one of the first to set up a purpose-built training ground. The team currently compete in the Premier League, the top tier of English football.'+
''+
'Burnley have been champions of England twice, in 1920–21 and 1959–60, have won the FA Cup once, in 1913–14, and have won the FA Charity Shield twice, in 1960 and 1973. They have been runners-up in the First Division twice, in 1919–20 and 1961–62, and FA Cup runners-up twice, in 1946–47 and 1961–62. The team also reached the quarter-finals of the 1960–61 European Cup. Burnley are one of only five sides to have won all four professional divisions of English football, along with Wolverhampton Wanderers, Preston North End, Sheffield United and Portsmouth. When the team won the 1959–60 Football League, the town of Burnley became the smallest to have an English first tier champion.'+
''+
'The team have played home games at Turf Moor since 1883, after they had moved from their original premises at Calder Vale. The club colours of claret and blue were adopted before the 1910–11 season in tribute to the then Football League champions Aston Villa. The club is nicknamed "the Clarets", because of the dominant colour of its home shirts. Burnley\'s current emblem is based on the town\'s coat of arms. The team have a long-standing rivalry with nearby club Blackburn Rovers, with whom they contest the East Lancashire Derby.';
	

const Chelsea = 'Chelsea Football Club is an English professional football club based in Fulham, London. Founded in 1905, the club competes in the Premier League, the top division of English football. Chelsea are among England\'s most successful clubs, having won over thirty competitive honours, including six league titles and six European trophies. Their home ground is Stamford Bridge.[4]'+
''+
'Chelsea won their first major honour, the League championship, in 1955. The club won the FA Cup for the first time in 1970 and their first European honour, the Cup Winners\' Cup, in 1971. After a period of decline in the late 1970s and 1980s, the club enjoyed a revival in the 1990s and had more success in cup competitions. The past two decades have been the most successful in Chelsea\'s history: they won five Premier League titles and both the UEFA Champions League and UEFA Europa League during this period.[5] Chelsea are one of five clubs to have won all three of UEFA\'s main club competitions, the first English club to achieve the UEFA treble, and the only London club to have won the Champions League.'+
''+
'Chelsea\'s home kit colours are royal blue shirts and shorts with white socks. The club\'s crest features a ceremonial lion rampant regardant holding a staff.[6] The club has rivalries with neighbouring teams Arsenal and Tottenham Hotspur, and a historic rivalry with Leeds United. Based on attendance figures, the club has the sixth-largest fanbase in England.[7] In terms of club value, Chelsea are the sixth most valuable football club in the world, worth £2.13 billion ($2.576 billion), and are the eighth highest-earning football club in the world, with earnings of over €428 million in the 2017–18 season.[8][9] Since 2003, Chelsea have been owned by Russian billionaire Roman Abramovich.[10]';
	

const Crystal_Palace = 'Crystal Palace Football Club is a professional football club based in Selhurst, South London, England, who currently compete in the Premier League, the highest level of English football. Although their official founding date is 1905, the club claim to be a continuation of the original amateur Crystal Palace football club first established in 1861, which would make them the oldest professional football club in the world,[1] after historians discovered a direct lineage through their ownership under the same Crystal Palace Company.[5][6] Both the amateur and professional clubs played inside the grounds of the Crystal Palace Exhibition building, with the professional club using the FA Cup Final stadium for its home games until 1915, when they were forced to leave due to the outbreak of the First World War. In 1924, they moved to their current home at Selhurst Park.'+
''+
'The amateur club became one of the original founder members of the Football Association in 1863 and competed in the first ever FA Cup competition in 1871–72, reaching the semi-finals, but disappeared from historical records after the 1875–76 FA Cup. Shortly after Crystal Palace returned to existence in 1905 as a professional club, they applied for election to the Football League, but were rejected and instead played in the Southern League. Palace did eventually join the Football League in 1920, and have overall spent the majority of their league history competing in the top two tiers of English football. Since 1964, they have only dropped below the second tier once, for three seasons between 1974 and 1977. During their period in the top flight in the late 1980s and early 1990s, the club achieved their highest ever league finish of third place in the old First Division, now known as the Premier League, in the 1990–91 season. Palace were unfortunate to miss out on qualification for the UEFA Cup at the end of that season due to the limited number of European places available to English clubs after the lifting of the UEFA ban caused by the Heysel Stadium disaster. It was also during this period that Palace reached the 1990 FA Cup Final losing to Manchester United after a replay, but they won the Full Members Cup the following year beating Everton in the final. The club became founder members of the Premier League in 1992. Following their relegation from the Premier League in 1998, Palace went into decline after suffering financial problems which resulted in the club going into administration twice in 1999 and 2010, but they recovered and returned to the Premier League in 2013 where they have remained ever since, and reached another FA Cup final in 2016, again finishing runners-up to Manchester United.'+
''+
'The club\'s kit colours were claret and blue until 1973, but then they decided to change to the red and blue vertical stripes worn today. Palace have a long-standing and fierce rivalry with Brighton & Hove Albion,[7] with whom they contest the M23 derby, and also share rivalries with fellow South London clubs Millwall and Charlton Athletic.';


const Everton = 'Everton Football Club (/ˈɛvərtən/) is an English professional football club based in Liverpool that competes in the Premier League, the top tier of English football. The club has competed in the top division for a record 117 seasons, missing only four top-flight seasons (1930–31, 1951–52, 1952–53, 1953–54) since the creation of the Football League, of which it was a founding member. Everton are the second-longest continuous serving club in English top flight football[2] and has won nine league titles, five FA Cups, one European Cup Winners\' Cup and nine Charity Shields.'+
''+
'Formed in 1878, Everton won their first League Championship during the 1890–91 season. After winning four more League Championships and two FA Cups, the club experienced a post-World War II lull until a revival in the 1960s. A period of sustained success came in the mid-1980s, when Everton won a further two League Championships, one FA Cup, and the 1985 European Cup Winners\' Cup. The club\'s most recent major trophy was the 1995 FA Cup.'+
''+
'The club\'s supporters are colloquially known as "Evertonians" or "Blues". Everton\'s main rivals are Liverpool, whose home stadium at Anfield is just under one mile away from Everton\'s home at Goodison Park, and the two clubs contest the Merseyside derby. Everton has been based at Goodison Park since 1892, having moved from its original home at Anfield following a disagreement over its rent. The club\'s home colours are royal blue shirts with white shorts and socks.Everton was founded as St Domingo FC in 1878[3][4] so that members of the congregation of St Domingo Methodist New Connexion Chapel in Breckfield Road North, Everton could play sport year round – cricket was played in summer. The club\'s first game was a 1–0 victory over Everton Church Club.[5] The club was renamed Everton in November 1879 after the local area, as people outside the congregation wished to participate.[5][6]'+
''+
'The club was a founding member of the Football League in 1888–89 and won its first League Championship title in the 1890–91 season. Everton won the FA Cup for the first time in 1906 and the League Championship again in 1914–15. The outbreak of World War I in 1914 interrupted the football programme while Everton reigned, which was something that would again occur in 1939.[7][8]';
	

const Fulham = 'Fulham Football Club is an English professional association football club based in Fulham, London. They currently compete in the Premier League, the highest level of the English football league system. Founded in 1879, they are London\'s oldest football club playing professionally.[4]'+
''+
'The club has spent 27 seasons in English football\'s top division, the majority of which have come in two periods during the 1960s and 2000s. The latter period was associated with former chairman Mohamed Al-Fayed, after the club had climbed up from the fourth tier in the 1990s. Fulham have reached two major finals: in 1975 they lost 2–0 against West Ham United in the FA Cup Final as a Second Division team, and in 2010 they played Atlético Madrid in the UEFA Europa League Final, losing 2–1 after extra time.'+
''+
'Fulham\'s main rivalries are with fellow West London clubs Chelsea, Queens Park Rangers and Brentford. The club adopted a white shirt and black shorts as its kit in 1903, which has been used ever since.[5].'+
'Fulham were formed in 1879 as Fulham St Andrew\'s Church Sunday School F.C.,[6] founded by worshipers (mostly adept at cricket) at the Church of England on Star Road, West Kensington (St Andrew\'s, Fulham Fields). Fulham\'s mother church still stands today with a plaque commemorating the team\'s foundation. They won the West London Amateur Cup in 1887 and, having shortened the name from Fulham St Andrews to its present form in December 1888, they then won the West London League in 1893 at the first attempt.[7] One of the club\'s first ever kits was half red, half white shirts with white shorts worn in the 1886–87 season.[8] Fulham started playing at their current ground at Craven Cottage in 1896, their first game against now defunct rivals Minerva. Fulham are one of the oldest established clubs in southern England currently playing professional football, though there are many non-league sides like Kent side Cray Wanderers who are several decades older.'+
''+
''+
'Postcard of the 1903–04 line-up'+
'The club gained professional status on 12 December 1898, the same year that they were admitted into the Southern League\'s Second Division. They were the third club from London to turn professional, following Arsenal, then named Royal Arsenal 1891, and Millwall in 1893. They adopted a red and white kit during the 1896-97 season.[9] In 1902–03, the club won promotion from this division, entering the Southern League First Division. The club\'s first recorded all-white club kit came in 1903, and ever since then the club has been playing in all-white shirts and black shorts, with socks going through various evolutions of black and/or white, but are now normally white-only.[10] The club won the Southern League twice, in 1905–06 and 1906–07.';


const Leeds_United = 'Leeds United Football Club is an English professional football club based in the city of Leeds, West Yorkshire. The club was formed in 1919 following the disbanding of Leeds City by the Football League and took over their Elland Road stadium. The club currently competes in the Premier League, the top flight of English football, following promotion from the EFL Championship during the 2019—20 season. Most of their history has been spent competing in the first tier of English football. Their longest continuous spell inside the first tier was a period of 18 years between 1964 and 1982, while their longest period outside of it spanned 16 years between 2004 and 2020.'+
''+
'They have won three English league titles, one FA Cup, one League Cup, two Charity/Community Shields and two Inter-Cities Fairs Cups. The club reached the 1975 European Cup Final, losing to Bayern Munich. Leeds reached the semi-finals of the tournament\'s successor, the Champions League in 2001.[3] The club were also runners-up in the European Cup Winners Cup final in 1973. The majority of the honours were won under the management of Don Revie in the 1960s and 1970s.'+
''+
'Leeds play in all-white kits at home matches. The club\'s badge features the White Rose of York. The club\'s anthem is an original song released in 1972, "Marching on Together". Leeds share rivalries with Manchester United and Chelsea, as well as with local teams such as Huddersfield Town, Bradford City, Sheffield United and Sheffield Wednesday';


const Leicester_City =  'Leicester City Football Club is a professional football club based in Leicester in the East Midlands, England. The club competes in the Premier League, the top division of England\'s football league system, and plays its home matches at the King Power Stadium.[2]'+
''+
'The club was founded in 1884 as Leicester Fosse F.C.,[3] playing on a field near Fosse Road. They moved to Filbert Street in 1891, were elected to the Football League in 1894 and adopted the name Leicester City in 1919. They moved to the nearby Walkers Stadium in 2002,[4] which was renamed the King Power Stadium in 2011.[5]'+
''+
'Leicester hold a joint-record seven second tier titles and have competed in four FA Cup finals; the only major English football honour the club is yet to win. They have won the League Cup three times and in 2015–16 Leicester won the Premier League. It was the club\'s first top tier title and they became one of only seven clubs to have won the Premier League since its inception in 1992.'+
''+
'A number of newspapers described Leicester\'s 2015–16 title win as the greatest sporting shock ever; multiple bookmakers had never paid out at such long odds for any sport.[6][7][8] The club\'s previous highest finish was second place in the top flight, in 1928–29, then known as the First Division.Formed in 1884 by a group of old boys of Wyggeston School as "Leicester Fosse", the club joined The Football Association (FA) in 1890.[9] Before moving to Filbert Street in 1891, the club played at five different grounds, including Victoria Park south-east of the city centre and the Belgrave Road Cycle and Cricket Ground.[10] The club also joined the Midland League in 1891, and were elected to Division Two of the Football League in 1894 after finishing second. Leicester\'s first ever Football League game was a 4–3 defeat at Grimsby Town, with a first League win the following week, against Rotherham United at Filbert Street. The same season also saw the club\'s largest win to date, a 13–0 victory over Notts Olympic in an FA Cup qualifying game.[3] In 1907–08 the club finished as Second Division runners-up, gaining promotion to the First Division, the highest level of English football. However, the club were relegated after a single season which included the club\'s record defeat, a 12–0 loss against Nottingham Forest.[3][11]';


const LiverPool = 'Liverpool Football Club is a professional football club in Liverpool, England, that competes in the Premier League, the top tier of English football. Domestically, the club has won nineteen League titles, seven FA Cups, a record eight League Cups and fifteen FA Community Shields. In international competitions, the club has won six European Cups, more than any other English club, three UEFA Cups, four UEFA Super Cups (also English records) and one FIFA Club World Cup.'+
''+
'Founded in 1892, the club joined the Football League the following year and has played at Anfield since its formation. Liverpool established itself as a major force in English and European football in the 1970s and 1980s, when Bill Shankly, Bob Paisley, Joe Fagan and Kenny Dalglish led the club to a combined eleven League titles and four European Cups. Liverpool won two further European Cups in 2005 and 2019 under the management of Rafael Benítez and Jürgen Klopp, respectively, the latter of whom led Liverpool to a nineteenth League title in 2020, the club\'s first during the Premier League era.'+
''+
'One of the most widely supported teams in the world,[3] in 2019, Liverpool was the world\'s seventh-highest-earning football club, with an annual revenue of €604 million,[4] and the world\'s eighth-most-valuable football club, valued at $2.183 billion.[5] Liverpool has long-standing rivalries with Manchester United and Everton. The team changed from red shirts and white shorts to an all-red home strip in 1964 which has been used ever since. The club\'s anthem is "You\'ll Never Walk Alone".'+
''+
'The club\'s supporters have been involved in two major tragedies: the Heysel Stadium disaster, where escaping fans were pressed against a collapsing wall at the 1985 European Cup Final in Brussels, with 39 people – mostly Italians and Juventus fans – dying, after which English clubs were given a five-year ban from European competition; and the Hillsborough disaster in 1989, where 96 Liverpool supporters died in a crush against perimeter fencing, which led to the elimination of fenced standing terraces in favour of all-seater stadiums in the top two tiers of English football.[6][7]';


const Manchester_City = 'Manchester City Football Club is an English football club based in Manchester that competes in the Premier League, the top flight of English football. Founded in 1880 as St. Mark\'s (West Gorton), it became Ardwick Association Football Club in 1887 and Manchester City in 1894. The club\'s home ground is the City of Manchester Stadium in east Manchester, to which it moved in 2003, having played at Maine Road since 1923. The club adopted their sky blue home shirts in 1894 in the first season of the club\'s current iteration, that have been used ever since.[4]'+
''+
'Manchester City entered the Football League in 1892, and won their first major honour with the FA Cup in 1904. The club had its first major period of success in the late 1960s, winning the League, European Cup Winners Cup, FA Cup and League Cup under the management of Joe Mercer and Malcolm Allison. After losing the 1981 FA Cup Final, the club went through a period of decline, culminating in relegation to the third tier of English football for the only time in its history in 1998. They since regained promotion to the top tier in 2001–02 and have remained a fixture in the Premier League since 2002–03.'+
''+
'In 2008, Manchester City was purchased by Abu Dhabi United Group for £210 million and received considerable financial investment in both playing staff and club facilities, including the £150 million Etihad Campus in east Manchester.[5] Under the management of Pep Guardiola they won the Premier League in 2018 becoming the only Premier League team to attain 100 points in a single season. In 2019, they won four trophies, completing an unprecedented sweep of all domestic trophies in England and becoming the first English men\'s team to win the domestic treble.[6]'+
''+
'Manchester City\'s revenue was the fifth highest of a football club in the world in the 2018–19 season at €568.4 million.[7] In 2019, Forbes estimated the club was the fifth most valuable in the world at $2.69 billion,[8] The club is owned by the City Football Group, a British-based[9] holding company valued at £3.73 (US$4.8) billion in November 2019 following a 10% stake sale to Silver Lake.[10]';


const Manchester_United = 'Manchester United Football Club is a professional football club based in Old Trafford, Greater Manchester, England, that competes in the Premier League, the top flight of English football. Nicknamed "the Red Devils", the club was founded as Newton Heath LYR Football Club in 1878, changed its name to Manchester United in 1902 and moved to its current stadium, Old Trafford, in 1910.'+
''+
'Manchester United have won more trophies than any other club in English football,[5][6] with a record 20 League titles, 12 FA Cups, five League Cups and a record 21 FA Community Shields. United have also won three UEFA Champions Leagues, one UEFA Europa League, one UEFA Cup Winners\' Cup, one UEFA Super Cup, one Intercontinental Cup and one FIFA Club World Cup. In 1998–99, the club became the first in the history of English football to achieve the continental European treble.[7] By winning the UEFA Europa League in 2016–17, they became one of five clubs to have won all three main UEFA club competitions.'+
''+
'The 1958 Munich air disaster claimed the lives of eight players. In 1968, under the management of Matt Busby, Manchester United became the first English football club to win the European Cup. Alex Ferguson won 38 trophies as manager, including 13 Premier League titles, 5 FA Cups and 2 UEFA Champions Leagues, between 1986 and 2013,[8][9][10] when he announced his retirement. Manchester United is one of the most widely supported football clubs in the world,[11][12] and has rivalries with Liverpool, Manchester City, Arsenal and Leeds United.'+
''+
'Manchester United was the highest-earning football club in the world for 2016–17, with an annual revenue of €676.3 million,[13] and the world\'s third most valuable football club in 2019, valued at £3.15 billion ($3.81 billion).[14] After being floated on the London Stock Exchange in 1991, the club was taken private after a purchase by Malcolm Glazer in 2005 at almost £800 million, of which over £500 million of borrowed money became the club\'s debt.[15] From 2012, some shares of the club were listed on the New York Stock Exchange, although the Glazer family retains overall ownership and control of the club.';


const Newcastle_United = 'Newcastle United Football Club is an English professional football club based in Newcastle upon Tyne, Tyne and Wear, that plays in the Premier League, the top flight of English football. Founded in 1892 by the merger of Newcastle East End and Newcastle West End. The team plays its home matches at St. James\' Park. Per the Taylor Report\'s requirement that all Premier League clubs have an all-seater stadium, the ground was adjusted in the mid-1990s and now has a capacity of 52,305.'+
''+
'The club has been a member of the Premier League for all but three years of the competition\'s history, spending 88 seasons in the top flight as of July 2020, and have never dropped below English football\'s second tier since joining the Football League in 1893. Newcastle have won 4 League titles, 6 FA Cups and a Charity Shield, as well as the 1969 Inter-Cities Fairs Cup and the 2006 UEFA Intertoto Cup, the ninth highest total of trophies won by an English club.[2] The club\'s most successful period was between 1904 and 1910, when they won an FA Cup and three of their League titles. Newcastle were relegated in 2009, and again in 2016. The club won promotion at the first time of asking each time, returning to the Premier League, as Championship winners, in 2010 and 2017.'+
''+
'Newcastle have a long-standing rivalry with nearby club Sunderland, with whom they have contested the Tyne–Wear derby since 1898. The club\'s traditional kit colours are black and white striped shirts, black shorts and black socks. Their crest has elements of the city coat of arms, which features two grey seahorses. Before each home game, the team enters the field to "Local Hero", and "Blaydon Races" is also sung during games.[3]'+
''+
'The club has been owned by Mike Ashley since 2007, succeeding long-term chairman Sir John Hall. The club is the 17th-highest revenue producing club in the world in terms of annual revenue, generating €169.3 million in 2015. Newcastle\'s highest placing was in 1999, when they were the fifth-highest revenue producing football club in the world, and second in England only behind Manchester United.[4]';



const Sheffield_United = 'heffield United Football Club is a professional football club in Sheffield, South Yorkshire, England, which competes in the Premier League, the top division of English football. They formed in 1889, as an offshoot of Sheffield United Cricket Club, and are nicknamed The Blades due to Sheffield\'s history of steel production.[2] They have played home games at Bramall Lane since their formation.'+
''+
'Sheffield United won the original Football League in 1898 and the FA Cup in 1899, 1902, 1915 and 1925. They were beaten finalists in the FA Cup in 1901 and 1936, and reached the semi-finals in 1961, 1993, 1998, 2003 and 2014. They reached the semi-finals of the League Cup in 2003 and 2015.'+
''+
'Sheffield United were the first club in English football to achieve promotion from the newly formed Second Division to the First Division in 1892–93. The club was also a founder member of the Premier League in the 1992–93 season, during which they scored the first ever goal of the Premier League era. Brian Deane was the scorer of the first goal in a 2–1 win at Bramall Lane, against the eventual champions, Manchester United.'+
''+
'Since the club\'s formation, they have played in tiers 1 through to 4 of the football league. They are one of only four clubs to have finished as champions of each of the top four tiers of the football league. Most of the club\'s history however has been spent in tier 1.'+
''+
'For most of the club\'s history they have played in red and white striped shirts with black shorts. Their closest rivals are Sheffield Wednesday, with whom they contest the Steel City derby.The club was formed by members of the Sheffield United Cricket Club, formed in 1854 and the first English sports club to use \'United\' in its name. Sheffield United\'s predominant nickname is "The Blades", a reference to Sheffield\'s status as the major producer of cutlery in the United Kingdom. United\'s original nickname was in fact "The Cutlers" from 1889–1912. City rivals Wednesday held the nickname "The Blades" in their early years, however in 1907 Wednesday officially became "The Owls", in reference to their new ground in Owlerton, and United would later claim "The Blades" nickname for themselves.[3]';


const Southhampton = 'Southampton Football Club (/saʊθˈ(h)æmptən/ (About this soundlisten)) is an English professional football club based in Southampton, Hampshire, which plays in the Premier League, the top tier of English football. One of the founding members of the Premier League, they have spent the majority of their history in the top flight since their first promotion to it in 1966; their longest continuous period was for 27 seasons between 1978 and 2005.'+
''+
'Their home ground since 2001 has been St Mary\'s Stadium, prior to which they were based at The Dell. The club has been nicknamed "The Saints" since its inception in 1885 due to its history as a church football team, founded as St. Mary\'s Church of England Young Men\'s Association, and play in red and white shirts. Southampton have a long-standing rivalry with Portsmouth, due in part to geographic proximity and both cities\' respective maritime histories. Matches between the two clubs are known as the South Coast derby.Southampton were originally founded at St. Mary\'s Church, on 21 November 1885 by members of the St. Mary\'s Church of England Young Men\'s Association.'+
''+
'St. Mary\'s Y.M.A., as they were usually referred to in the local press, played most of their early games on The Common where games were frequently interrupted by pedestrians insistent on exercising their right to roam. More important matches, such as cup games, were played either at the County Cricket Ground in Northlands Road or the Antelope Cricket Ground in St Mary\'s Road.'+
''+
'The club was originally known as St. Mary\'s Young Men\'s Association F.C. (usually abbreviated to "St. Mary\'s Y.M.A.") and then became simply St. Mary\'s F.C. in 1887–88, before adopting the name Southampton St. Mary\'s when the club joined the Southern League in 1894.';
	

const Tottenham_Hotspur = 'Tottenham Hotspur Football Club, commonly referred to as Tottenham (/ˈtɒtənəm/)[2][3] or Spurs, is an English professional football club in Tottenham, London, that competes in the Premier League. Tottenham Hotspur Stadium has been the club\'s home ground since April 2019, replacing their former home of White Hart Lane, which had been demolished to make way for the new stadium on the same site. Their training ground is on Hotspur Way in Bulls Cross in the London Borough of Enfield. The club is owned by ENIC Group. Tottenham have played in a first (home) strip of white shirts and navy blue shorts since the 1898–99 season. The club\'s emblem is a cockerel standing upon a football, with a Latin motto Audere est Facere ("To Dare Is to Do").'+
''+
'Founded in 1882, Tottenham won the FA Cup for the first time in 1901, the only non-League club to do so since the formation of the Football League in 1888. Tottenham were the first club in the 20th century to achieve the League and FA Cup Double, winning both competitions in the 1960–61 season. After successfully defending the FA Cup in 1962, in 1963 they became the first British club to win a UEFA club competition – the European Cup Winners\' Cup.[4] They were also the inaugural winners of the UEFA Cup in 1972, becoming the first British club to win two different major European trophies. They collected at least one major trophy in each of the six decades from the 1950s to 2000s – an achievement only matched by Manchester United.[5][6] In total, Spurs have won two league titles, eight FA Cups, four League Cups, seven FA Community Shields, one European Cup Winners\' Cup and two UEFA Cups. Tottenham were also the runners-up in the 2018–19 UEFA Champions League. They have a long-standing rivalry with nearby club Arsenal, with whom they contest the North London derby.Originally named Hotspur Football Club, the club was formed on 5 September 1882 by a group of schoolboys led by Bobby Buckle. They were members of the Hotspur Cricket Club and the football club was formed to play sports during the winter months.[7] A year later the boys sought help with the club from John Ripsher, the Bible class teacher at All Hallows Church, who became the first president of the club and its treasurer. Ripsher helped and supported the boys through the club\'s formative years, reorganised and found premises for the club.[8][9][10] In April 1884 the club was renamed "Tottenham Hotspur Football Club" to avoid confusion with another London club named Hotspur, whose post had been mistakenly delivered to North London.[11][12] Nicknames for the club include "Spurs" and "the Lilywhites".[13]';


const brom = 'West Bromwich Albion Football Club (/ˈbrɒmɪdʒ, -ɪtʃ/) is an English professional football club based in West Bromwich, West Midlands, England, that competes in the Premier League, the top tier of English football. The club was formed in 1878 and has played at its home ground, The Hawthorns, since 1900.'+
''+
'Albion was one of the 12 founding members of the Football League in 1888, the first professional football league in the world. The club has spent the majority of its existence in the top tier of English football, where as of 2020–21 it has played for 82 seasons. The club has been champions of England once, in 1919–20, and has been runners-up twice. Albion teams have reached ten FA Cup finals and won the Cup on five occasions. The first win came in 1888, the year the league was founded, and the most recent in 1968, the club\'s last major trophy. It also won the Football League Cup at the first attempt in 1966. The club\'s longest continuous period in the top division spanned 24 years between 1949 and 1973, and from 1986 to 2002 it spent its longest ever spell out of the top division.'+
''+
'The team has played in navy blue and white stripes for most of the club\'s history, and the club badge features a throstle perched on a hawthorn branch. Albion has a number of long-standing rivalries with other West Midlands clubs, with its traditional rivals being Aston Villa and Wolves. Albion contests the Black Country derby with the latter.The club was founded as West Bromwich Strollers in 1878 by workers from George Salter\'s Spring Works in West Bromwich, in the Black Country .[A][2] They were renamed West Bromwich Albion in 1880, becoming the first team to adopt the Albion suffix; Albion was a district of West Bromwich where some of the players lived or worked, close to what is today Greets Green.[2] The club joined the Birmingham & District Football Association in 1881 and became eligible for their first competition, the Birmingham Cup. They reached the quarter-finals, beating several longer-established clubs on the way. In 1883, Albion won their first trophy, the Staffordshire Cup. Albion joined the Football Association in the same year; this enabled them to enter the FA Cup for the first time in the 1883–84 season.[3] In 1885 the club turned professional,[4] and in 1886 they reached the FA Cup final for the first time, losing 2–0 to Blackburn Rovers in a replay. They reached the final again in 1887, but lost 2–0 to Aston Villa. In 1888 the team won the trophy for the first time, beating strong favourites Preston North End 2–1 in the final.[5] As FA Cup winners, they qualified to play in a Football World Championship game against Scottish Cup winners Renton, which ended in a 4–1 defeat.[6]';


const west_ham = 'West Ham United Football Club is an English professional football club based in Stratford, East London. They compete in the Premier League, the top tier of English football. The club plays at the London Stadium, having moved from their former home the Boleyn Ground in 2016.'+
''+
'The club was founded in 1895 as Thames Ironworks and reformed in 1900 as West Ham United. They moved to the Boleyn Ground in 1904, which remained their home ground for more than a century. The team initially competed in the Southern League and Western League before joining the Football League in 1919. They were promoted to the top flight in 1923, when they were also losing finalists in the first FA Cup Final held at Wembley. In 1940, the club won the inaugural Football League War Cup.'+
''+
'West Ham have been winners of the FA Cup three times; in 1964, 1975 and 1980, and have also been runners-up twice; in 1923 and 2006. The club have reached two major European finals, winning the European Cup Winners\' Cup in 1965 and finishing runners-up in the same competition in 1976. West Ham also won the Intertoto Cup in 1999. They are one of eight clubs never to have fallen below the second tier of English football, spending 63 of 95 league seasons in the top flight, up to and including the 2020-21 season. The club\'s highest league position to date came in 1985–86, when they achieved third place in the then First Division.'+
''+
'Three West Ham players were members of the 1966 World Cup final-winning England team: captain Bobby Moore and goalscorers Geoff Hurst and Martin Peters. The club has a long-standing rivalry with Millwall. West Ham adopted their claret and sky blue colour scheme in the early 1900s, with the most common iteration of a claret shirt and sky blue sleeves first emerging in 1904.[4]';


const wol = 'Wolverhampton Wanderers Football Club (/ˌwʊlvərˈhæmptən/ (About this soundlisten)), commonly known as Wolves, is a professional association football club based in the city of Wolverhampton in the West Midlands, England. Formed as St. Luke\'s F.C. in 1877, the club has played at Molineux Stadium since 1889 and has been competing in the Premier League, the top division of English football, since winning promotion in 2018. The 2020–21 season is the club\'s 66th season in total at the highest level.'+
''+
'The club was one of the founding members of the Football League in 1888. During 26 consecutive seasons spent in the top flight between 1932 and 1965,[nb 1] it was English League champions three times (in 1953–54, 1957–58 and 1958–59), all under the management of Stan Cullis. Wolves also finished English league runners-up in five other seasons between 1937–38 and 1959–60.'+
''+
'Wolves has won the FA Cup four times, most recently in 1960, and finished runners-up on a further four occasions. The club has also won the League Cup twice, in 1974 and 1980, and finished top of all four divisions in the English professional game.'+
''+
'After becoming one of the first British clubs to install floodlights, Wolves arranged televised "floodlit friendlies" against leading overseas club sides between 1953 and 1956, which were instrumental in the launch of the European Cup (now known as the UEFA Champions League) in 1955. Wolves reached the quarter-finals of the competition in 1959–60 as well as the semi-finals of the 1960–61 European Cup Winners\' Cup and the inaugural UEFA Cup Final in 1972. Following a 39-year absence from European competition, they reached the UEFA Europa League quarter-finals in 2020.'+
''+
'Wolves\' traditional kit consists of old gold shirts and socks and black shorts. Since 1979, the kit has also featured the club\'s "wolf\'s head" badge. Long-standing rivalries exist with other West Midlands clubs, the main one being the Black Country derby contested with West Bromwich Albion. The two clubs played one another during the 2020–21 season for the first time since 2011–12, the Premier League game on 16 January 2021 coming nearly nine years since the previous meeting on 12 February 2012.';

const data = {};

function initData(){
    data['Arsenal'] = Arsenal;
    data['Aston Villa'] = Aston_Villa;
    data['Brighton and Hove Albion'] = brighton;
    data['Burnley'] = burnley;
    data['Chelsea'] = Chelsea;
    data['Crystal Palace'] = Crystal_Palace;
    data['Everton'] = Everton;
    data['Fulham'] = Fulham;
    data['Leeds United'] = Leeds_United;
    data['Leicester City'] = Leicester_City;
    data['Liverpool'] = LiverPool;
    data['Manchester City'] = Manchester_City;
    data['Manchester United'] = Manchester_United;
    data['Newcastle United'] = Newcastle_United;
    data['Sheffield United'] = Sheffield_United;
    data['Southampton'] = Southhampton;
    data['Tottenham Hotspur'] = Tottenham_Hotspur;
    data['West Bromwich Albion'] = brom;
    data['West Ham United'] = west_ham;
    data['Wolverhampton Wanderers'] = wol;


}

initData();


export const stadium = {
    'Arsenal':  "Emirates Stadium",
    'Aston Villa' :  "Villa Park",
    'Brighton and Hove Albion':  "American Express",
    'Burnley': "Turf Moor",
    'Chelsea':  "Stamford Bridge",
    'Crystal Palace':  "Selhurst Park Stadium",
    'Everton':  "Goodison Park",
    'Fulham':  "Craven Cottage",
    'Leeds United':  "Elland Road",
    'Leicester City':  "King Power Stadium",
    'Liverpool':  "Anfield",
    'Manchester City':  "Etihad Stadium",
    'Manchester United':  "Old Trafford",
    'Newcastle United':  "St.James Park",
    'Sheffield United':  "Bramall Lane",
    'Southampton':  "St Mary's Stadium",
    'Tottenham Hotspur':  "White Heart Lane",
    'West Bromwich Albion':  "West Bromwich Stadium",
    'West Ham United':  "London Stadium",
    'Wolverhampton Wanderers':  "Molineux Stadium",
};



export function getTeamInfo(team){
    return data[team];
}